# Generated by Django 4.0 on 2021-12-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('pret_salarial', models.FloatField()),
                ('disp_trab_imed', models.CharField(max_length=10)),
                ('idade', models.DateTimeField()),
            ],
        ),
    ]
