# Generated by Django 4.0 on 2021-12-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('pret_salarial', models.FloatField(verbose_name='pret_salarial')),
                ('disp_trab_imed', models.BooleanField(verbose_name='disp_trab_imed')),
                ('idade', models.DateField(verbose_name='idade')),
            ],
        ),
    ]
