# Generated by Django 4.0 on 2021-12-22 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('cpf', models.CharField(editable=False, max_length=11, unique=True, verbose_name='cpf')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('pret_salarial', models.FloatField(verbose_name='Pretenção Salarial')),
                ('disp_trab_imed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Disponibilidade Imediata de Trabalho')),
                ('idade', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)], verbose_name='idade')),
            ],
        ),
    ]
