# Generated by Django 4.0 on 2021-12-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='cpf',
            field=models.CharField(editable=False, max_length=11, verbose_name='cpf'),
        ),
    ]
