# Generated by Django 4.0 on 2021-12-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_candidatos_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='cpf'),
        ),
    ]
