# Generated by Django 4.0 on 2021-12-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_candidatos_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='disp_trab_imed',
            field=models.BooleanField(verbose_name='Disponibilidade Imediata de Trabalho'),
        ),
    ]
